### PR TITLE
Simplify user_select_file() method using only tkinter.

### PR DESCRIPTION
**Pull request by rhosbach**
Used tkinter only to simplify the user_select_file() method in tools.py.  Please test on multiple OSs, if possible.

### CODE REVIEW

**Comment by lyralan** [comment]
Thanks Rob! Happy to see this being implemented in a more consistent and concise way. 

It works for me on MacOS. I circled around folks who have used linux to run programs, and they just manually type the path to be read in the run script, because the "prompt" is by nature not compatible with linux, unless one sets up something like VNC viewer, which needs to be installed (by admin) on the server. So there might not be a need to test `user_select_file` on linux. Feel free to share your thoughts on this!

Otherwise it looks pretty good! I think it's good to go as is. Let me know if there's anything else that I might have missed!

**Comment by 0xd5dc** [comment]
I tested it with LCC and had no issue using this branch.

**Comment by lyralan** [comment]
Hi all - it's been quite a while and no one seems to have requested changes. I'm going to approve this PR by Friday as I think this is good to go as is after testing it on my computer, and I don't think this PR should linger forever.

**Comment by rhosbach** [comment]
Thanks, @lyralan.  Completely agreed.  @milicag did you have any thoughts before we approve/merge?

**Comment by milicag** [comment]
All good here!

**Review by lyralan — APPROVED** [review]
Thanks again Rob!

**Pull request merged**
